### ISSUE TITLE
VS2015 becoming slow

### ISSUE THREAD

**Issue by kipusoep** [TomChantler/Always-Admin-VS#2]
I've used this tool to run VS2015 Enterprise as admin on Windows 8.1 and ran into an issue.
When VS2015 is running for a while (2 hours for example), it becomes very very slow. When I just run devenv.exe, this problem doesn't occur.

**Comment by TomChantler** [comment]
That's very odd, I haven't heard of anybody else experiencing this. It seems unlikely, but we should leave the issue open in case anyone else has noticed it too.

**Comment by TomChantler** [comment]
I reckon I'll close this as nobody else has ever reported this issue.

**Comment by kipusoep** [comment]
Everybody's using VS2017 nowadays ;-) And I didn't run into this with 2017, so no problem closing the issue :-)
